@url = http://localhost:5079
@customerId = be7ae22e-499a-4f92-86a4-7e01f767a7a8
@depositId = dc39b2ea-ebab-429c-aa77-55cbdfee46d9
@withdrawalIban = PL10105000997603123456789123


###
GET {{url}}/deposits/accounts

###
GET {{url}}/deposits

###
POST {{url}}/deposits
Content-Type: application/json

{
  "customerId": "{{customerId}}",
  "currency": "PLN",
  "amount": "5000"
}

###
PUT {{url}}/deposits/{{depositId}}/complete
Content-Type: application/json

{
  "secret": "secret"
}

###
GET {{url}}/withdrawals/accounts

###
POST {{url}}/withdrawals/accounts
Content-Type: application/json

{
  "currency": "PLN",
  "iban": "{{withdrawalIban}}"
}

###
GET {{url}}/withdrawals

###
POST {{url}}/withdrawals
Content-Type: application/json

{
  "currency": "PLN",
  "amount": "1000"
}