@url = http://localhost:5079/customers
@customerId = 90bfbdf3-0d2f-4ebc-bca2-854c6d7935f8

POST {{url}}
Content-Type: application/json

{
  "email": "test@gmail.com"
}

###

GET {{url}}/{{customerId}}
