@url = http://localhost:5079/customers
@customerId = 2d8f2b98-19d6-4936-8b90-1027cf744425

### CREATE A NEW CUSTOMER

POST {{url}}
Content-Type: application/json

{
  "email": "user13@inflow.io"
}

### GET CUSTOMER BY ID

GET {{url}}/{{customerId}}


###
PUT {{url}}/complete
Content-Type: application/json

{
  "customerId": "{{customerId}}",
  "name": "cha2",
  "fullName": "John Doee",
  "address": "Test street 123",
  "nationality": "PL",
  "identityType": "id_card",
  "identitySeries": "ABC1234567"
}

###
PUT {{url}}/{{customerId}}/verify
Content-Type: application/json

{
}

###
PUT {{url}}/{{customerId}}/lock
Content-Type: application/json

{
}

###
PUT {{url}}/{{customerId}}/unlock
Content-Type: application/json

{
  "notes" : "oi"
}