@url = http://localhost:5079
@transferId = 00000000-0000-0000-0000-000000000001
@ownerId = be7ae22e-499a-4f92-86a4-7e01f767a7a8
@walletId = cf30faa3-99e8-4b08-9d91-05bb5da5cef5
@receiverWalletId = 9174b699-b2c6-46a8-9ce6-4a691aeae4d0

###
GET {{url}}/transfers

###
GET {{url}}/transfers/{{walletId}}

###
POST {{url}}/transfers/incoming
Content-Type: application/json

{
  "walletId": "{{walletId}}",
  "currency": "PLN",
  "amount": "1000",
  "transferName": "test123",
  "transferMetadata": "lorem ipsum metadata"
}

###
POST {{url}}/transfers/outgoing
Content-Type: application/json

{
  "walletId": "{{walletId}}",
  "currency": "PLN",
  "amount": "500",
  "transferName": "test123",
  "transferMetadata": "lorem ipsum metadata"
}


###
POST {{url}}/transfers/funds
Content-Type: application/json

{
  "ownerId" : "{{ownerId}}",
  "ownerWalletId": "{{walletId}}",
  "receiverWalletId": "{{receiverWalletId}}",
  "currency": "PLN",
  "amount": "200"
}


###
GET {{url}}/wallets

###
GET {{url}}/wallets/{{walletId}}

